-- MySQL Script generated by MySQL Workbench
-- Sat Mar 25 18:16:13 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema kereta_api
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `kereta_api` ;

-- -----------------------------------------------------
-- Schema kereta_api
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kereta_api` DEFAULT CHARACTER SET utf8 ;
USE `kereta_api` ;

-- -----------------------------------------------------
-- Table `kereta_api`.`customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kereta_api`.`customers` ;

CREATE TABLE IF NOT EXISTS `kereta_api`.`customers` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `alamat` VARCHAR(100) NOT NULL,
  `nomor_telepon` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kereta_api`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kereta_api`.`user` ;

CREATE TABLE IF NOT EXISTS `kereta_api`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kereta_api`.`transportation_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kereta_api`.`transportation_type` ;

CREATE TABLE IF NOT EXISTS `kereta_api`.`transportation_type` (
  `transportation_type_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`transportation_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kereta_api`.`transportation_company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kereta_api`.`transportation_company` ;

CREATE TABLE IF NOT EXISTS `kereta_api`.`transportation_company` (
  `transportation_company_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `contact` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`transportation_company_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kereta_api`.`rute`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kereta_api`.`rute` ;

CREATE TABLE IF NOT EXISTS `kereta_api`.`rute` (
  `rute_id` INT NOT NULL AUTO_INCREMENT,
  `stasiun_asal` VARCHAR(255) NOT NULL,
  `stasiun_tujuan` VARCHAR(255) NOT NULL,
  `jarak` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`rute_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kereta_api`.`transportation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kereta_api`.`transportation` ;

CREATE TABLE IF NOT EXISTS `kereta_api`.`transportation` (
  `transportation_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `transportation_type_id` INT NOT NULL,
  `transportation_company_id` INT NOT NULL,
  PRIMARY KEY (`transportation_id`),
  CONSTRAINT `fk_transportation_transportation_company`
    FOREIGN KEY (`transportation_company_id`)
    REFERENCES `kereta_api`.`transportation_company` (`transportation_company_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_transportation_transportation_type`
    FOREIGN KEY (`transportation_type_id`)
    REFERENCES `kereta_api`.`transportation_type` (`transportation_type_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_transportation_transportation_company_id` ON `kereta_api`.`transportation` (`transportation_company_id` ASC) VISIBLE;

CREATE INDEX `fk_transportation_transportation_type_id` ON `kereta_api`.`transportation` (`transportation_type_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `kereta_api`.`transportation_class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kereta_api`.`transportation_class` ;

CREATE TABLE IF NOT EXISTS `kereta_api`.`transportation_class` (
  `transportation_class_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `harga` DECIMAL(10,2) NOT NULL,
  `transportation_id` INT NOT NULL,
  PRIMARY KEY (`transportation_class_id`),
  CONSTRAINT `fk_transportation_class_transportation`
    FOREIGN KEY (`transportation_id`)
    REFERENCES `kereta_api`.`transportation` (`transportation_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_transportation_class_transportation_id` ON `kereta_api`.`transportation_class` (`transportation_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `kereta_api`.`jadwal_keberangkatan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kereta_api`.`jadwal_keberangkatan` ;

CREATE TABLE IF NOT EXISTS `kereta_api`.`jadwal_keberangkatan` (
  `jadwal_keberangkatan_id` INT NOT NULL AUTO_INCREMENT,
  `waktu_berangkat` DATETIME NOT NULL,
  `transportation_id` INT NOT NULL,
  `rute_id` INT NOT NULL,
  PRIMARY KEY (`jadwal_keberangkatan_id`),
  CONSTRAINT `fk_jadwal_keberangkatan_transportation`
    FOREIGN KEY (`transportation_id`)
    REFERENCES `kereta_api`.`transportation` (`transportation_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_jadwal_keberangkatan_rute`
    FOREIGN KEY (`rute_id`)
    REFERENCES `kereta_api`.`rute` (`rute_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_jadwal_keberangkatan_transportation_id` ON `kereta_api`.`jadwal_keberangkatan` (`transportation_id` ASC) VISIBLE;

CREATE INDEX `fk_jadwal_keberangkatan_rute_id` ON `kereta_api`.`jadwal_keberangkatan` (`rute_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `kereta_api`.`reservation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kereta_api`.`reservation` ;

CREATE TABLE IF NOT EXISTS `kereta_api`.`reservation` (
  `reservation_id` INT NOT NULL AUTO_INCREMENT,
  `tanggal_reservasi` DATETIME NOT NULL,
  `jumlah_tiket` INT NOT NULL,
  `total_harga` DECIMAL(10,2) NOT NULL,
  `jadwal_keberangkatan_id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  PRIMARY KEY (`reservation_id`),
  CONSTRAINT `fk_reservasi_jadwal_keberangkatan`
    FOREIGN KEY (`jadwal_keberangkatan_id`)
    REFERENCES `kereta_api`.`jadwal_keberangkatan` (`jadwal_keberangkatan_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_reservasi_customers`
    FOREIGN KEY (`customer_id`)
    REFERENCES `kereta_api`.`customers` (`customer_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_reservasi_jadwal_keberangkatan_id` ON `kereta_api`.`reservation` (`jadwal_keberangkatan_id` ASC) VISIBLE;

CREATE INDEX `fk_reservasi_customers_id` ON `kereta_api`.`reservation` (`customer_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `kereta_api`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kereta_api`.`order` ;

CREATE TABLE IF NOT EXISTS `kereta_api`.`order` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `tanggal_order` DATETIME NOT NULL,
  `status` ENUM('Pending', 'Confirmed', 'Cancelled') NOT NULL,
  `reservation_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`order_id`),
  CONSTRAINT `fk_order_reservation`
    FOREIGN KEY (`reservation_id`)
    REFERENCES `kereta_api`.`reservation` (`reservation_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_order_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `kereta_api`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_order_reservation_id` ON `kereta_api`.`order` (`reservation_id` ASC) VISIBLE;

CREATE INDEX `fk_order_user_id` ON `kereta_api`.`order` (`user_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `kereta_api`.`payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kereta_api`.`payment` ;

CREATE TABLE IF NOT EXISTS `kereta_api`.`payment` (
  `payment_id` INT NOT NULL AUTO_INCREMENT,
  `tanggal_pembayaran` DATETIME NOT NULL,
  `jumlah` DECIMAL(10,2) NOT NULL,
  `metode_pembayaran` ENUM('cash', 'credit_card', 'debit_card') NOT NULL,
  `order_id` INT NOT NULL,
  PRIMARY KEY (`payment_id`),
  CONSTRAINT `fk_payment_order`
    FOREIGN KEY (`order_id`)
    REFERENCES `kereta_api`.`order` (`order_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_payment_order_id` ON `kereta_api`.`payment` (`order_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
