#!/bin/bash

# create main directory with timestamp
main_dir_name="$1_$(date +'%a_%b_%d_%H:%M:%S_%Y')"
mkdir "$main_dir_name"

# create subdirectories
personal_dir="$main_dir_name/about_me/personal"
professional_dir="$main_dir_name/about_me/professional"
friends_dir="$main_dir_name/my_friends"
system_info_dir="$main_dir_name/my_system_info"
mkdir -p "$personal_dir" "$professional_dir" "$friends_dir" "$system_info_dir"

# create files with content
echo "My username: $USER" > "$system_info_dir/about_this_laptop.txt"
echo "With host: $(uname -a)" >> "$system_info_dir/about_this_laptop.txt"
echo "https://www.facebook.com/$2" > "$personal_dir/facebook.txt"
echo "https://www.linkedin.com/in/$3" > "$professional_dir/linkedin.txt"
curl -o "$friends_dir/list_of_my_friends.txt" "https://raw.githubusercontent.com/rahmandikahaekal/simple-cli/master/list_of_my_friends.txt"
ping -c 3 forcesafesearch.google.com > "$system_info_dir/internet_connection.txt"

# print directory structure
tree "$main_dir_name"
